/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Addresses controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, AddressDetailsListResponse, AddressDetailsResponse, AddressUpdate, ObjectResponse, AddressCreate } from "../models";

@Injectable({ providedIn: "root" })
export class AddressesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    addressesAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressDetailsListResponse>;
    addressesAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressDetailsListResponse>>;
    addressesAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressDetailsListResponse>>;
    addressesAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    addressesIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressDetailsResponse>;
    addressesIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressDetailsResponse>>;
    addressesIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressDetailsResponse>>;
    addressesIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    addressesIdPut(id: string, addressUpdate?: AddressUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressDetailsResponse>;
    addressesIdPut(id: string, addressUpdate?: AddressUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressDetailsResponse>>;
    addressesIdPut(id: string, addressUpdate?: AddressUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressDetailsResponse>>;
    addressesIdPut(id: string, addressUpdate?: AddressUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, addressUpdate, requestOptions);
    }

    addressesIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    addressesIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    addressesIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    addressesIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    addressesUserUserIdGet(userId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressDetailsListResponse>;
    addressesUserUserIdGet(userId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressDetailsListResponse>>;
    addressesUserUserIdGet(userId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressDetailsListResponse>>;
    addressesUserUserIdGet(userId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses/user/${userId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    addressesPost(addressCreate?: AddressCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<AddressDetailsResponse>;
    addressesPost(addressCreate?: AddressCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AddressDetailsResponse>>;
    addressesPost(addressCreate?: AddressCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AddressDetailsResponse>>;
    addressesPost(addressCreate?: AddressCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/addresses`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, addressCreate, requestOptions);
    }
}
