/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Auth controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { UserCreate, RequestOptions, UserDetailsResponse, UserUpdateInput, UserLogin, LoginOutputResponse, StringResponse, UserInfosWithtokenResponse, ForgotPasswordInput, PasswordResetOutputResponse, PasswordRecoveryInput, ObjectResponse, FileUrlResponse } from "../models";

@Injectable({ providedIn: "root" })
export class AuthService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    authRegisterPost(userCreate?: UserCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserDetailsResponse>;
    authRegisterPost(userCreate?: UserCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserDetailsResponse>>;
    authRegisterPost(userCreate?: UserCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserDetailsResponse>>;
    authRegisterPost(userCreate?: UserCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/register`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, userCreate, requestOptions);
    }

    authUpdatePatch(userUpdateInput?: UserUpdateInput, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserDetailsResponse>;
    authUpdatePatch(userUpdateInput?: UserUpdateInput, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserDetailsResponse>>;
    authUpdatePatch(userUpdateInput?: UserUpdateInput, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserDetailsResponse>>;
    authUpdatePatch(userUpdateInput?: UserUpdateInput, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/update`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, userUpdateInput, requestOptions);
    }

    authLoginPost(userLogin?: UserLogin, observe?: 'body', options?: RequestOptions<'json'>): Observable<LoginOutputResponse>;
    authLoginPost(userLogin?: UserLogin, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LoginOutputResponse>>;
    authLoginPost(userLogin?: UserLogin, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LoginOutputResponse>>;
    authLoginPost(userLogin?: UserLogin, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/login`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, userLogin, requestOptions);
    }

    authEmailConfirmationGet(userId?: string, confirmationToken?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<StringResponse>;
    authEmailConfirmationGet(userId?: string, confirmationToken?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<StringResponse>>;
    authEmailConfirmationGet(userId?: string, confirmationToken?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<StringResponse>>;
    authEmailConfirmationGet(userId?: string, confirmationToken?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/email-confirmation`;

        let params = new HttpParams();
        if (userId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, userId, 'userId');
        }
        if (confirmationToken != null) {
            params = HttpParamsBuilder.addToHttpParams(params, confirmationToken, 'confirmationToken');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    authMyInformationsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<UserInfosWithtokenResponse>;
    authMyInformationsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserInfosWithtokenResponse>>;
    authMyInformationsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserInfosWithtokenResponse>>;
    authMyInformationsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/my-informations`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    authPublicInformationsGet(userId?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserDetailsResponse>;
    authPublicInformationsGet(userId?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserDetailsResponse>>;
    authPublicInformationsGet(userId?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserDetailsResponse>>;
    authPublicInformationsGet(userId?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/public-informations`;

        let params = new HttpParams();
        if (userId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, userId, 'userId');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    authForgotPasswordPost(forgotPasswordInput?: ForgotPasswordInput, observe?: 'body', options?: RequestOptions<'json'>): Observable<PasswordResetOutputResponse>;
    authForgotPasswordPost(forgotPasswordInput?: ForgotPasswordInput, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PasswordResetOutputResponse>>;
    authForgotPasswordPost(forgotPasswordInput?: ForgotPasswordInput, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PasswordResetOutputResponse>>;
    authForgotPasswordPost(forgotPasswordInput?: ForgotPasswordInput, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/forgot-password`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, forgotPasswordInput, requestOptions);
    }

    authResetPasswordPost(passwordRecoveryInput?: PasswordRecoveryInput, observe?: 'body', options?: RequestOptions<'json'>): Observable<StringResponse>;
    authResetPasswordPost(passwordRecoveryInput?: PasswordRecoveryInput, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<StringResponse>>;
    authResetPasswordPost(passwordRecoveryInput?: PasswordRecoveryInput, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<StringResponse>>;
    authResetPasswordPost(passwordRecoveryInput?: PasswordRecoveryInput, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/reset-password`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, passwordRecoveryInput, requestOptions);
    }

    authRefreshTokenGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<LoginOutputResponse>;
    authRefreshTokenGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LoginOutputResponse>>;
    authRefreshTokenGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LoginOutputResponse>>;
    authRefreshTokenGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/refresh-token`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    authLogoutGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    authLogoutGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    authLogoutGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    authLogoutGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/logout`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    authUploadAvatarPost(file?: Blob, observe?: 'body', options?: RequestOptions<'json'>): Observable<FileUrlResponse>;
    authUploadAvatarPost(file?: Blob, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FileUrlResponse>>;
    authUploadAvatarPost(file?: Blob, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FileUrlResponse>>;
    authUploadAvatarPost(file?: Blob, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/auth/upload-avatar`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (file !== undefined) {
            formData.append('file', file);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }
}
