/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for CategoryCursus controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CategoryCursusDetailsListResponse, CategoryCursusDetailsResponse, CategoryCursusUpdate, ObjectResponse, CategoryCursusCreate } from "../models";

@Injectable({ providedIn: "root" })
export class CategoryCursusService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    categorycursusAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryCursusDetailsListResponse>;
    categorycursusAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryCursusDetailsListResponse>>;
    categorycursusAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryCursusDetailsListResponse>>;
    categorycursusAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categorycursus/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    categorycursusIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryCursusDetailsResponse>;
    categorycursusIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryCursusDetailsResponse>>;
    categorycursusIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryCursusDetailsResponse>>;
    categorycursusIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categorycursus/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    categorycursusIdPut(id: string, categoryCursusUpdate?: CategoryCursusUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryCursusDetailsResponse>;
    categorycursusIdPut(id: string, categoryCursusUpdate?: CategoryCursusUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryCursusDetailsResponse>>;
    categorycursusIdPut(id: string, categoryCursusUpdate?: CategoryCursusUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryCursusDetailsResponse>>;
    categorycursusIdPut(id: string, categoryCursusUpdate?: CategoryCursusUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categorycursus/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, categoryCursusUpdate, requestOptions);
    }

    categorycursusIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    categorycursusIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    categorycursusIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    categorycursusIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categorycursus/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    categorycursusPost(categoryCursusCreate?: CategoryCursusCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategoryCursusDetailsResponse>;
    categorycursusPost(categoryCursusCreate?: CategoryCursusCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategoryCursusDetailsResponse>>;
    categorycursusPost(categoryCursusCreate?: CategoryCursusCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategoryCursusDetailsResponse>>;
    categorycursusPost(categoryCursusCreate?: CategoryCursusCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/categorycursus`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, categoryCursusCreate, requestOptions);
    }
}
