/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Cursus controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CursusDetailsListResponse, CursusDetailsResponse, ObjectResponse, CursusCreate, CursusUpdate } from "../models";

@Injectable({ providedIn: "root" })
export class CursusService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    cursusAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<CursusDetailsListResponse>;
    cursusAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CursusDetailsListResponse>>;
    cursusAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CursusDetailsListResponse>>;
    cursusAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/cursus/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    cursusIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CursusDetailsResponse>;
    cursusIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CursusDetailsResponse>>;
    cursusIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CursusDetailsResponse>>;
    cursusIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/cursus/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    cursusIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    cursusIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    cursusIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    cursusIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/cursus/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    cursusTeacherIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CursusDetailsListResponse>;
    cursusTeacherIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CursusDetailsListResponse>>;
    cursusTeacherIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CursusDetailsListResponse>>;
    cursusTeacherIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/cursus/teacher/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    cursusLevelIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CursusDetailsListResponse>;
    cursusLevelIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CursusDetailsListResponse>>;
    cursusLevelIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CursusDetailsListResponse>>;
    cursusLevelIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/cursus/level/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    cursusCreatePost(cursusCreate?: CursusCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<CursusDetailsResponse>;
    cursusCreatePost(cursusCreate?: CursusCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CursusDetailsResponse>>;
    cursusCreatePost(cursusCreate?: CursusCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CursusDetailsResponse>>;
    cursusCreatePost(cursusCreate?: CursusCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/cursus/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, cursusCreate, requestOptions);
    }

    cursusUpdateIdPut(id: string, cursusUpdate?: CursusUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<CursusDetailsResponse>;
    cursusUpdateIdPut(id: string, cursusUpdate?: CursusUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CursusDetailsResponse>>;
    cursusUpdateIdPut(id: string, cursusUpdate?: CursusUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CursusDetailsResponse>>;
    cursusUpdateIdPut(id: string, cursusUpdate?: CursusUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/cursus/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, cursusUpdate, requestOptions);
    }
}
