/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Favorites controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { CreateFavorite, RequestOptions, FavoriteDetailsResponse, ObjectResponse, BooleanResponse } from "../models";

@Injectable({ providedIn: "root" })
export class FavoritesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    favoritesAddPost(createFavorite?: CreateFavorite, observe?: 'body', options?: RequestOptions<'json'>): Observable<FavoriteDetailsResponse>;
    favoritesAddPost(createFavorite?: CreateFavorite, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FavoriteDetailsResponse>>;
    favoritesAddPost(createFavorite?: CreateFavorite, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FavoriteDetailsResponse>>;
    favoritesAddPost(createFavorite?: CreateFavorite, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/add`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createFavorite, requestOptions);
    }

    favoritesRemoveTeacherIdDelete(teacherId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    favoritesRemoveTeacherIdDelete(teacherId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    favoritesRemoveTeacherIdDelete(teacherId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    favoritesRemoveTeacherIdDelete(teacherId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/remove/${teacherId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    favoritesIsFavoriteTeacherIdGet(teacherId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<BooleanResponse>;
    favoritesIsFavoriteTeacherIdGet(teacherId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<BooleanResponse>>;
    favoritesIsFavoriteTeacherIdGet(teacherId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<BooleanResponse>>;
    favoritesIsFavoriteTeacherIdGet(teacherId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/favorites/is-favorite/${teacherId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
