/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Files controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions } from "../models";

@Injectable({ providedIn: "root" })
export class FilesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    filesUploadPost(file?: Blob, folder?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    filesUploadPost(file?: Blob, folder?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    filesUploadPost(file?: Blob, folder?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    filesUploadPost(file?: Blob, folder?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/files/upload`;

        let params = new HttpParams();
        if (folder != null) {
            params = HttpParamsBuilder.addToHttpParams(params, folder, 'folder');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (file !== undefined) {
            formData.append('file', file);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    filesDownloadGet(path?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    filesDownloadGet(path?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    filesDownloadGet(path?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    filesDownloadGet(path?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/files/download`;

        let params = new HttpParams();
        if (path != null) {
            params = HttpParamsBuilder.addToHttpParams(params, path, 'path');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    filesDelete(path?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    filesDelete(path?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    filesDelete(path?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    filesDelete(path?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/files`;

        let params = new HttpParams();
        if (path != null) {
            params = HttpParamsBuilder.addToHttpParams(params, path, 'path');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
