/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Formations controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, FormationDetailsListResponse, FormationDetailsResponse, FormationUpdate, BooleanResponse, FormationCreate } from "../models";

@Injectable({ providedIn: "root" })
export class FormationsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    formationsAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<FormationDetailsListResponse>;
    formationsAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormationDetailsListResponse>>;
    formationsAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormationDetailsListResponse>>;
    formationsAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    formationsIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<FormationDetailsResponse>;
    formationsIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormationDetailsResponse>>;
    formationsIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormationDetailsResponse>>;
    formationsIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    formationsIdPut(id: string, formationUpdate?: FormationUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<FormationDetailsResponse>;
    formationsIdPut(id: string, formationUpdate?: FormationUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormationDetailsResponse>>;
    formationsIdPut(id: string, formationUpdate?: FormationUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormationDetailsResponse>>;
    formationsIdPut(id: string, formationUpdate?: FormationUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, formationUpdate, requestOptions);
    }

    formationsIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<BooleanResponse>;
    formationsIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<BooleanResponse>>;
    formationsIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<BooleanResponse>>;
    formationsIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    formationsTeacherIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<FormationDetailsListResponse>;
    formationsTeacherIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormationDetailsListResponse>>;
    formationsTeacherIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormationDetailsListResponse>>;
    formationsTeacherIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations/teacher/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    formationsPost(formationCreate?: FormationCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<FormationDetailsResponse>;
    formationsPost(formationCreate?: FormationCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormationDetailsResponse>>;
    formationsPost(formationCreate?: FormationCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormationDetailsResponse>>;
    formationsPost(formationCreate?: FormationCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/formations`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formationCreate, requestOptions);
    }
}
