/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated service exports
* Do not edit this file manually
*/
export { AddressesService } from "./addresses.service";
export { AuthService } from "./auth.service";
export { CategoryCursusService } from "./categoryCursus.service";
export { CursusService } from "./cursus.service";
export { FormationsService } from "./formations.service";
export { GendersService } from "./genders.service";
export { LanguagesService } from "./languages.service";
export { LevelCursusService } from "./levelCursus.service";
export { ProductService } from "./product.service";
export { RolesService } from "./roles.service";
export { SlotsService } from "./slots.service";
export { TeachersService } from "./teachers.service";
export { TypeAddressesService } from "./typeAddresses.service";
export { TypeSlotsService } from "./typeSlots.service";
