/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Languages controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, LanguageDetailsListResponse, LanguageCreate, LanguageDetailsResponse, LanguageUpdate, ObjectResponse } from "../models";

@Injectable({ providedIn: "root" })
export class LanguagesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    languagesAllPost(observe?: 'body', options?: RequestOptions<'json'>): Observable<LanguageDetailsListResponse>;
    languagesAllPost(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LanguageDetailsListResponse>>;
    languagesAllPost(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LanguageDetailsListResponse>>;
    languagesAllPost(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/languages/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }

    languagesUserGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<LanguageDetailsListResponse>;
    languagesUserGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LanguageDetailsListResponse>>;
    languagesUserGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LanguageDetailsListResponse>>;
    languagesUserGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/languages/user`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    languagesCreatePost(languageCreate?: LanguageCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<LanguageDetailsResponse>;
    languagesCreatePost(languageCreate?: LanguageCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LanguageDetailsResponse>>;
    languagesCreatePost(languageCreate?: LanguageCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LanguageDetailsResponse>>;
    languagesCreatePost(languageCreate?: LanguageCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/languages/create`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, languageCreate, requestOptions);
    }

    languagesUpdateIdPut(id: string, languageUpdate?: LanguageUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<LanguageDetailsResponse>;
    languagesUpdateIdPut(id: string, languageUpdate?: LanguageUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LanguageDetailsResponse>>;
    languagesUpdateIdPut(id: string, languageUpdate?: LanguageUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LanguageDetailsResponse>>;
    languagesUpdateIdPut(id: string, languageUpdate?: LanguageUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/languages/update/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, languageUpdate, requestOptions);
    }

    languagesDeleteIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    languagesDeleteIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    languagesDeleteIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    languagesDeleteIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/languages/delete/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    languagesTeacherUpdateLanguagesPost(requestBody?: Array<string>, observe?: 'body', options?: RequestOptions<'json'>): Observable<LanguageDetailsListResponse>;
    languagesTeacherUpdateLanguagesPost(requestBody?: Array<string>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LanguageDetailsListResponse>>;
    languagesTeacherUpdateLanguagesPost(requestBody?: Array<string>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LanguageDetailsListResponse>>;
    languagesTeacherUpdateLanguagesPost(requestBody?: Array<string>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/languages/teacher/update-languages`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, requestBody, requestOptions);
    }
}
