/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for LevelCursus controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, LevelCursusDetailsListResponse, LevelCursusDetailsResponse, ObjectResponse, LevelCursusCreate, LevelCursusUpdate } from "../models";

@Injectable({ providedIn: "root" })
export class LevelCursusService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    levelcursusAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelCursusDetailsListResponse>;
    levelcursusAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelCursusDetailsListResponse>>;
    levelcursusAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelCursusDetailsListResponse>>;
    levelcursusAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/levelcursus/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    levelcursusIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelCursusDetailsResponse>;
    levelcursusIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelCursusDetailsResponse>>;
    levelcursusIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelCursusDetailsResponse>>;
    levelcursusIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/levelcursus/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    levelcursusIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    levelcursusIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    levelcursusIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    levelcursusIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/levelcursus/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    levelcursusPost(levelCursusCreate?: LevelCursusCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelCursusDetailsResponse>;
    levelcursusPost(levelCursusCreate?: LevelCursusCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelCursusDetailsResponse>>;
    levelcursusPost(levelCursusCreate?: LevelCursusCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelCursusDetailsResponse>>;
    levelcursusPost(levelCursusCreate?: LevelCursusCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/levelcursus`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, levelCursusCreate, requestOptions);
    }

    levelcursusPut(levelCursusUpdate?: LevelCursusUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<LevelCursusDetailsResponse>;
    levelcursusPut(levelCursusUpdate?: LevelCursusUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LevelCursusDetailsResponse>>;
    levelcursusPut(levelCursusUpdate?: LevelCursusUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LevelCursusDetailsResponse>>;
    levelcursusPut(levelCursusUpdate?: LevelCursusUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/levelcursus`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, levelCursusUpdate, requestOptions);
    }
}
