/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Notifications controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { FilterNotification, RequestOptions, NotificationDetailsListResponse, NotificationDetailsResponse } from "../models";

@Injectable({ providedIn: "root" })
export class NotificationsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    notificationsPost(filterNotification?: FilterNotification, observe?: 'body', options?: RequestOptions<'json'>): Observable<NotificationDetailsListResponse>;
    notificationsPost(filterNotification?: FilterNotification, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<NotificationDetailsListResponse>>;
    notificationsPost(filterNotification?: FilterNotification, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<NotificationDetailsListResponse>>;
    notificationsPost(filterNotification?: FilterNotification, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/notifications`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, filterNotification, requestOptions);
    }

    notificationsIdToggleSeenPut(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<NotificationDetailsResponse>;
    notificationsIdToggleSeenPut(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<NotificationDetailsResponse>>;
    notificationsIdToggleSeenPut(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<NotificationDetailsResponse>>;
    notificationsIdToggleSeenPut(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/notifications/${id}/toggle-seen`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, null, requestOptions);
    }

    notificationsAllToggleSeenPut(observe?: 'body', options?: RequestOptions<'json'>): Observable<NotificationDetailsResponse>;
    notificationsAllToggleSeenPut(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<NotificationDetailsResponse>>;
    notificationsAllToggleSeenPut(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<NotificationDetailsResponse>>;
    notificationsAllToggleSeenPut(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/notifications/all-toggle-seen`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, null, requestOptions);
    }
}
