/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Payment controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { CheckoutRequest, RequestOptions, ObjectResponse, CreateAccountRequest, TransferRequest } from "../models";

@Injectable({ providedIn: "root" })
export class PaymentService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    paymentCheckoutPost(checkoutRequest?: CheckoutRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    paymentCheckoutPost(checkoutRequest?: CheckoutRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    paymentCheckoutPost(checkoutRequest?: CheckoutRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    paymentCheckoutPost(checkoutRequest?: CheckoutRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/payment/checkout`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, checkoutRequest, requestOptions);
    }

    paymentConnectAccountPost(createAccountRequest?: CreateAccountRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    paymentConnectAccountPost(createAccountRequest?: CreateAccountRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    paymentConnectAccountPost(createAccountRequest?: CreateAccountRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    paymentConnectAccountPost(createAccountRequest?: CreateAccountRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/payment/connect/account`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createAccountRequest, requestOptions);
    }

    paymentConnectTransferPost(transferRequest?: TransferRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    paymentConnectTransferPost(transferRequest?: TransferRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    paymentConnectTransferPost(transferRequest?: TransferRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    paymentConnectTransferPost(transferRequest?: TransferRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/payment/connect/transfer`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, transferRequest, requestOptions);
    }

    paymentWebhookPost(observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    paymentWebhookPost(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    paymentWebhookPost(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    paymentWebhookPost(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/payment/webhook`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, null, requestOptions);
    }
}
