/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Product controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, ProductDetailsListResponse, ProductDetailsResponse, ObjectResponse, ProductCreate, ProductUpdate } from "../models";

@Injectable({ providedIn: "root" })
export class ProductService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    productAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<ProductDetailsListResponse>;
    productAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ProductDetailsListResponse>>;
    productAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ProductDetailsListResponse>>;
    productAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/product/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    productIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ProductDetailsResponse>;
    productIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ProductDetailsResponse>>;
    productIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ProductDetailsResponse>>;
    productIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/product/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    productIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    productIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    productIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    productIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/product/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    productCursusIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ProductDetailsListResponse>;
    productCursusIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ProductDetailsListResponse>>;
    productCursusIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ProductDetailsListResponse>>;
    productCursusIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/product/cursus/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    productTeacherIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ProductDetailsListResponse>;
    productTeacherIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ProductDetailsListResponse>>;
    productTeacherIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ProductDetailsListResponse>>;
    productTeacherIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/product/teacher/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    productPost(productCreate?: ProductCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<ProductDetailsResponse>;
    productPost(productCreate?: ProductCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ProductDetailsResponse>>;
    productPost(productCreate?: ProductCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ProductDetailsResponse>>;
    productPost(productCreate?: ProductCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/product`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, productCreate, requestOptions);
    }

    productPut(productUpdate?: ProductUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<ProductDetailsResponse>;
    productPut(productUpdate?: ProductUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ProductDetailsResponse>>;
    productPut(productUpdate?: ProductUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ProductDetailsResponse>>;
    productPut(productUpdate?: ProductUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/product`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, productUpdate, requestOptions);
    }
}
