/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Slots controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { SlotCreate, RequestOptions, SlotDetailsResponse, SlotUpdate, BooleanResponse, SlotDetailsListResponse } from "../models";

@Injectable({ providedIn: "root" })
export class SlotsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    slotsTeacherAddPost(slotCreate?: SlotCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotDetailsResponse>;
    slotsTeacherAddPost(slotCreate?: SlotCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotDetailsResponse>>;
    slotsTeacherAddPost(slotCreate?: SlotCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotDetailsResponse>>;
    slotsTeacherAddPost(slotCreate?: SlotCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/add`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, slotCreate, requestOptions);
    }

    slotsTeacherUpdatePut(slotUpdate?: SlotUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotDetailsResponse>;
    slotsTeacherUpdatePut(slotUpdate?: SlotUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotDetailsResponse>>;
    slotsTeacherUpdatePut(slotUpdate?: SlotUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotDetailsResponse>>;
    slotsTeacherUpdatePut(slotUpdate?: SlotUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/update`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, slotUpdate, requestOptions);
    }

    slotsTeacherRemoveSlotIdDelete(slotId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<BooleanResponse>;
    slotsTeacherRemoveSlotIdDelete(slotId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<BooleanResponse>>;
    slotsTeacherRemoveSlotIdDelete(slotId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<BooleanResponse>>;
    slotsTeacherRemoveSlotIdDelete(slotId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/remove/${slotId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    slotsTeacherMySlotsGet(dateFrom?: Date, dateTo?: Date, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotDetailsListResponse>;
    slotsTeacherMySlotsGet(dateFrom?: Date, dateTo?: Date, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotDetailsListResponse>>;
    slotsTeacherMySlotsGet(dateFrom?: Date, dateTo?: Date, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotDetailsListResponse>>;
    slotsTeacherMySlotsGet(dateFrom?: Date, dateTo?: Date, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/my-slots`;

        let params = new HttpParams();
        if (dateFrom != null) {
            params = HttpParamsBuilder.addToHttpParams(params, dateFrom, 'dateFrom');
        }
        if (dateTo != null) {
            params = HttpParamsBuilder.addToHttpParams(params, dateTo, 'dateTo');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    slotsTeacherTeacherIdAvailableSlotsGet(teacherId: string, dateFrom?: Date, dateTo?: Date, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotDetailsListResponse>;
    slotsTeacherTeacherIdAvailableSlotsGet(teacherId: string, dateFrom?: Date, dateTo?: Date, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotDetailsListResponse>>;
    slotsTeacherTeacherIdAvailableSlotsGet(teacherId: string, dateFrom?: Date, dateTo?: Date, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotDetailsListResponse>>;
    slotsTeacherTeacherIdAvailableSlotsGet(teacherId: string, dateFrom?: Date, dateTo?: Date, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/${teacherId}/available-slots`;

        let params = new HttpParams();
        if (dateFrom != null) {
            params = HttpParamsBuilder.addToHttpParams(params, dateFrom, 'dateFrom');
        }
        if (dateTo != null) {
            params = HttpParamsBuilder.addToHttpParams(params, dateTo, 'dateTo');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
