/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Slots controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { SlotCreate, RequestOptions, SlotDetailsResponse, SlotUpdate, BooleanResponse, PeriodTime, SlotDetailsListResponse, CustomTableState, ReservationDetailsListResponse, ReservationCreate, ReservationUpdateStatus, ObjectResponse, ReservationDetailsResponse, ConversationDetailsListResponse } from "../models";

@Injectable({ providedIn: "root" })
export class SlotsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    slotsTeacherAddPost(slotCreate?: SlotCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotDetailsResponse>;
    slotsTeacherAddPost(slotCreate?: SlotCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotDetailsResponse>>;
    slotsTeacherAddPost(slotCreate?: SlotCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotDetailsResponse>>;
    slotsTeacherAddPost(slotCreate?: SlotCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/add`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, slotCreate, requestOptions);
    }

    slotsTeacherUpdatePut(slotUpdate?: SlotUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotDetailsResponse>;
    slotsTeacherUpdatePut(slotUpdate?: SlotUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotDetailsResponse>>;
    slotsTeacherUpdatePut(slotUpdate?: SlotUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotDetailsResponse>>;
    slotsTeacherUpdatePut(slotUpdate?: SlotUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/update`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, slotUpdate, requestOptions);
    }

    slotsTeacherRemoveSlotIdDelete(slotId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<BooleanResponse>;
    slotsTeacherRemoveSlotIdDelete(slotId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<BooleanResponse>>;
    slotsTeacherRemoveSlotIdDelete(slotId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<BooleanResponse>>;
    slotsTeacherRemoveSlotIdDelete(slotId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/remove/${slotId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    slotsTeacherMySlotsPost(periodTime?: PeriodTime, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotDetailsListResponse>;
    slotsTeacherMySlotsPost(periodTime?: PeriodTime, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotDetailsListResponse>>;
    slotsTeacherMySlotsPost(periodTime?: PeriodTime, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotDetailsListResponse>>;
    slotsTeacherMySlotsPost(periodTime?: PeriodTime, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/my-slots`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, periodTime, requestOptions);
    }

    slotsTeacherTeacherIdAvailableSlotsPost(teacherId: string, periodTime?: PeriodTime, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotDetailsListResponse>;
    slotsTeacherTeacherIdAvailableSlotsPost(teacherId: string, periodTime?: PeriodTime, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotDetailsListResponse>>;
    slotsTeacherTeacherIdAvailableSlotsPost(teacherId: string, periodTime?: PeriodTime, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotDetailsListResponse>>;
    slotsTeacherTeacherIdAvailableSlotsPost(teacherId: string, periodTime?: PeriodTime, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/${teacherId}/available-slots`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, periodTime, requestOptions);
    }

    slotsStudentPost(periodTime?: PeriodTime, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotDetailsListResponse>;
    slotsStudentPost(periodTime?: PeriodTime, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotDetailsListResponse>>;
    slotsStudentPost(periodTime?: PeriodTime, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotDetailsListResponse>>;
    slotsStudentPost(periodTime?: PeriodTime, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/student`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, periodTime, requestOptions);
    }

    slotsStudentReservationsPost(customTableState?: CustomTableState, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReservationDetailsListResponse>;
    slotsStudentReservationsPost(customTableState?: CustomTableState, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReservationDetailsListResponse>>;
    slotsStudentReservationsPost(customTableState?: CustomTableState, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReservationDetailsListResponse>>;
    slotsStudentReservationsPost(customTableState?: CustomTableState, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/student/reservations`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, customTableState, requestOptions);
    }

    slotsTeacherReservationsPost(customTableState?: CustomTableState, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReservationDetailsListResponse>;
    slotsTeacherReservationsPost(customTableState?: CustomTableState, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReservationDetailsListResponse>>;
    slotsTeacherReservationsPost(customTableState?: CustomTableState, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReservationDetailsListResponse>>;
    slotsTeacherReservationsPost(customTableState?: CustomTableState, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/reservations`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, customTableState, requestOptions);
    }

    slotsStudentBookPost(reservationCreate?: ReservationCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<SlotDetailsListResponse>;
    slotsStudentBookPost(reservationCreate?: ReservationCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SlotDetailsListResponse>>;
    slotsStudentBookPost(reservationCreate?: ReservationCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SlotDetailsListResponse>>;
    slotsStudentBookPost(reservationCreate?: ReservationCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/student/book`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, reservationCreate, requestOptions);
    }

    slotsTeacherConfirmReservationPost(reservationUpdateStatus?: ReservationUpdateStatus, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    slotsTeacherConfirmReservationPost(reservationUpdateStatus?: ReservationUpdateStatus, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    slotsTeacherConfirmReservationPost(reservationUpdateStatus?: ReservationUpdateStatus, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    slotsTeacherConfirmReservationPost(reservationUpdateStatus?: ReservationUpdateStatus, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/confirm-reservation`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, reservationUpdateStatus, requestOptions);
    }

    slotsReservationReservationIdGet(reservationId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReservationDetailsResponse>;
    slotsReservationReservationIdGet(reservationId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReservationDetailsResponse>>;
    slotsReservationReservationIdGet(reservationId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReservationDetailsResponse>>;
    slotsReservationReservationIdGet(reservationId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/reservation/${reservationId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    slotsConversationReservationIdGet(reservationId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ConversationDetailsListResponse>;
    slotsConversationReservationIdGet(reservationId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ConversationDetailsListResponse>>;
    slotsConversationReservationIdGet(reservationId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ConversationDetailsListResponse>>;
    slotsConversationReservationIdGet(reservationId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/conversation/${reservationId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    slotsTeacherRemoveReservationDelete(reservationId?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    slotsTeacherRemoveReservationDelete(reservationId?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    slotsTeacherRemoveReservationDelete(reservationId?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    slotsTeacherRemoveReservationDelete(reservationId?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/teacher/remove-reservation`;

        let params = new HttpParams();
        if (reservationId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, reservationId, 'reservationId');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    slotsStudentRemoveReservationDelete(reservationId?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ObjectResponse>;
    slotsStudentRemoveReservationDelete(reservationId?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ObjectResponse>>;
    slotsStudentRemoveReservationDelete(reservationId?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ObjectResponse>>;
    slotsStudentRemoveReservationDelete(reservationId?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/slots/student/remove-reservation`;

        let params = new HttpParams();
        if (reservationId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, reservationId, 'reservationId');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }
}
