/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Teachers controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { FilterTeacher, RequestOptions, UserDetailsListResponse, UserDetailsResponse, UserUpdate, PrivacyDocumentDetailsListResponse, PrivacyDocumentDetailsResponse, PrivacyDocumentTypeDetailsListResponse } from "../models";

@Injectable({ providedIn: "root" })
export class TeachersService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    teachersAllPost(filterTeacher?: FilterTeacher, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserDetailsListResponse>;
    teachersAllPost(filterTeacher?: FilterTeacher, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserDetailsListResponse>>;
    teachersAllPost(filterTeacher?: FilterTeacher, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserDetailsListResponse>>;
    teachersAllPost(filterTeacher?: FilterTeacher, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teachers/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, filterTeacher, requestOptions);
    }

    teachersMyProfileGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<UserDetailsResponse>;
    teachersMyProfileGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserDetailsResponse>>;
    teachersMyProfileGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserDetailsResponse>>;
    teachersMyProfileGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teachers/my-profile`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    teachersUserUserIdGet(userId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserDetailsResponse>;
    teachersUserUserIdGet(userId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserDetailsResponse>>;
    teachersUserUserIdGet(userId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserDetailsResponse>>;
    teachersUserUserIdGet(userId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teachers/user/${userId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    teachersUpdateProfilePut(userUpdate?: UserUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserDetailsResponse>;
    teachersUpdateProfilePut(userUpdate?: UserUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserDetailsResponse>>;
    teachersUpdateProfilePut(userUpdate?: UserUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserDetailsResponse>>;
    teachersUpdateProfilePut(userUpdate?: UserUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teachers/update-profile`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, userUpdate, requestOptions);
    }

    teachersGetDocumentsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<PrivacyDocumentDetailsListResponse>;
    teachersGetDocumentsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PrivacyDocumentDetailsListResponse>>;
    teachersGetDocumentsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PrivacyDocumentDetailsListResponse>>;
    teachersGetDocumentsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teachers/get-documents`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    teachersUploadDocumentPost(Title: string, TypeId: string, File: Blob, Description?: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<PrivacyDocumentDetailsResponse>;
    teachersUploadDocumentPost(Title: string, TypeId: string, File: Blob, Description?: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PrivacyDocumentDetailsResponse>>;
    teachersUploadDocumentPost(Title: string, TypeId: string, File: Blob, Description?: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PrivacyDocumentDetailsResponse>>;
    teachersUploadDocumentPost(Title: string, TypeId: string, File: Blob, Description?: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teachers/upload-document`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (Title !== undefined) {
            formData.append('Title', String(Title));
        }
        if (Description !== undefined) {
            formData.append('Description', String(Description));
        }
        if (TypeId !== undefined) {
            formData.append('TypeId', String(TypeId));
        }
        if (File !== undefined) {
            formData.append('File', File);
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, formData, requestOptions);
    }

    teachersDocumentTypesGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<PrivacyDocumentTypeDetailsListResponse>;
    teachersDocumentTypesGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PrivacyDocumentTypeDetailsListResponse>>;
    teachersDocumentTypesGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PrivacyDocumentTypeDetailsListResponse>>;
    teachersDocumentTypesGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teachers/document-types`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
