/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for TeacherProfile controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, TeacherDetailsListResponse, TeacherDetailsResponse, TeacherProfileUpdate } from "../models";

@Injectable({ providedIn: "root" })
export class TeacherProfileService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    teacherprofileAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<TeacherDetailsListResponse>;
    teacherprofileAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TeacherDetailsListResponse>>;
    teacherprofileAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TeacherDetailsListResponse>>;
    teacherprofileAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teacherprofile/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    teacherprofileMyProfileGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<TeacherDetailsResponse>;
    teacherprofileMyProfileGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TeacherDetailsResponse>>;
    teacherprofileMyProfileGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TeacherDetailsResponse>>;
    teacherprofileMyProfileGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teacherprofile/my-profile`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    teacherprofileUserUserIdGet(userId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<TeacherDetailsResponse>;
    teacherprofileUserUserIdGet(userId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TeacherDetailsResponse>>;
    teacherprofileUserUserIdGet(userId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TeacherDetailsResponse>>;
    teacherprofileUserUserIdGet(userId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teacherprofile/user/${userId}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    teacherprofilePut(teacherProfileUpdate?: TeacherProfileUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<TeacherDetailsResponse>;
    teacherprofilePut(teacherProfileUpdate?: TeacherProfileUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TeacherDetailsResponse>>;
    teacherprofilePut(teacherProfileUpdate?: TeacherProfileUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TeacherDetailsResponse>>;
    teacherprofilePut(teacherProfileUpdate?: TeacherProfileUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/teacherprofile`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, teacherProfileUpdate, requestOptions);
    }
}
