/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for TypeSlots controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, TypeSlotDetailsListResponse, TypeSlotDetailsResponse, BooleanResponse, TypeSlotCreate, TypeSlotUpdate } from "../models";

@Injectable({ providedIn: "root" })
export class TypeSlotsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    typeslotsAllGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<TypeSlotDetailsListResponse>;
    typeslotsAllGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TypeSlotDetailsListResponse>>;
    typeslotsAllGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TypeSlotDetailsListResponse>>;
    typeslotsAllGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/typeslots/all`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    typeslotsIdGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<TypeSlotDetailsResponse>;
    typeslotsIdGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TypeSlotDetailsResponse>>;
    typeslotsIdGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TypeSlotDetailsResponse>>;
    typeslotsIdGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/typeslots/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    typeslotsIdDelete(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<BooleanResponse>;
    typeslotsIdDelete(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<BooleanResponse>>;
    typeslotsIdDelete(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<BooleanResponse>>;
    typeslotsIdDelete(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/typeslots/${id}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    typeslotsPost(typeSlotCreate?: TypeSlotCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<TypeSlotDetailsResponse>;
    typeslotsPost(typeSlotCreate?: TypeSlotCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TypeSlotDetailsResponse>>;
    typeslotsPost(typeSlotCreate?: TypeSlotCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TypeSlotDetailsResponse>>;
    typeslotsPost(typeSlotCreate?: TypeSlotCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/typeslots`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, typeSlotCreate, requestOptions);
    }

    typeslotsPut(typeSlotUpdate?: TypeSlotUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<TypeSlotDetailsResponse>;
    typeslotsPut(typeSlotUpdate?: TypeSlotUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TypeSlotDetailsResponse>>;
    typeslotsPut(typeSlotUpdate?: TypeSlotUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TypeSlotDetailsResponse>>;
    typeslotsPut(typeSlotUpdate?: TypeSlotUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/typeslots`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.put(url, typeSlotUpdate, requestOptions);
    }
}
