/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for UserManagement controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { FilterUserManagement, RequestOptions, UserDetailsListResponse, TeacherDetailsResponse } from "../models";

@Injectable({ providedIn: "root" })
export class UserManagementService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    usermanagementTeachersPost(filterUserManagement?: FilterUserManagement, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserDetailsListResponse>;
    usermanagementTeachersPost(filterUserManagement?: FilterUserManagement, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserDetailsListResponse>>;
    usermanagementTeachersPost(filterUserManagement?: FilterUserManagement, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserDetailsListResponse>>;
    usermanagementTeachersPost(filterUserManagement?: FilterUserManagement, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/usermanagement/teachers`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, filterUserManagement, requestOptions);
    }

    usermanagementTeachersUserIdConfirmationPatch(userId: string, isConfirmed?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<TeacherDetailsResponse>;
    usermanagementTeachersUserIdConfirmationPatch(userId: string, isConfirmed?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<TeacherDetailsResponse>>;
    usermanagementTeachersUserIdConfirmationPatch(userId: string, isConfirmed?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<TeacherDetailsResponse>>;
    usermanagementTeachersUserIdConfirmationPatch(userId: string, isConfirmed?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/usermanagement/teachers/${userId}/confirmation`;

        let params = new HttpParams();
        if (isConfirmed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, isConfirmed, 'isConfirmed');
        }

        const requestOptions: any = {
            observe: observe as any,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.patch(url, null, requestOptions);
    }
}
