/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface FileUrl {
    url?: string | null;
}

export interface FileUrlResponseDTO {
    message: string;
    status: number;
    data?: FileUrl;
    count?: number | null;
}

export interface ForgotPasswordInput {
    email: string;
}

export interface GenderDTO {
    readonly id: string;
    readonly name: string;
    readonly color: string;
    readonly icon?: string | null;
}

export interface LoginOutputDTO {
    token: string;
    refreshToken: string;
    user: UserDetailsDTO;
}

export interface LoginOutputDTOResponseDTO {
    message: string;
    status: number;
    data?: LoginOutputDTO;
    count?: number | null;
}

export interface ObjectResponseDTO {
    message: string;
    status: number;
    data?: any | null;
    count?: number | null;
}

export interface PasswordRecoveryInput {
    userId: string;
    resetToken: string;
    password: string;
    passwordConfirmation: string;
}

export interface PasswordResetResponseDTO {
    resetToken: string;
    email: string;
    id: string;
}

export interface PasswordResetResponseDTOResponseDTO {
    message: string;
    status: number;
    data?: PasswordResetResponseDTO;
    count?: number | null;
}

export interface RoleAppDetailsDTO {
    id: string;
    name: string;
    normalizedName?: string | null;
    color?: string | null;
    displayName?: string | null;
    createdAt: Date;
    updatedAt?: Date | null;
}

export interface StringResponseDTO {
    message: string;
    status: number;
    data?: string | null;
    count?: number | null;
}

export interface UserCreateDTO {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    dataProcessingConsent: boolean;
    privacyPolicyConsent: boolean;
    title?: string | null;
    description?: string | null;
    phoneNumber?: string | null;
    dateOfBirth?: Date;
    roleId?: string;
    genderId?: string;
}

export interface UserDetailsDTO {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    dateOfBirth?: Date;
    title?: string | null;
    description?: string | null;
    phoneNumber?: string | null;
    imgUrl?: string | null;
    gender?: GenderDTO;
    createdAt?: Date;
    roles: Array<RoleAppDetailsDTO>;
}

export interface UserDetailsDTOResponseDTO {
    message: string;
    status: number;
    data?: UserDetailsDTO;
    count?: number | null;
}

export interface UserInfosWithtoken {
    token: string;
    user: UserDetailsDTO;
}

export interface UserInfosWithtokenResponseDTO {
    message: string;
    status: number;
    data?: UserInfosWithtoken;
    count?: number | null;
}

export interface UserLoginDTO {
    email: string;
    password: string;
}

export interface UserUpdateDTO {
    firstName: string;
    lastName: string;
    dateOfBirth: Date;
    title?: string | null;
    description?: string | null;
    phoneNumber?: string | null;
    languagesIds?: Array<string>;
    programmingLanguagesIds?: Array<string>;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
